const userScore = o;
const computerScore =0;
const userScore_span = document.getElementById("user-Score");
const computerScore_span = document.getElementById("computer-Score");
const ScoreBoard_div = document.querySelector("result");
const result_div = document.querySelector("result");
const rock_div = document.getElementById("r");
const paper_div = document.getElementById("p");
const scrssorce_div = document.getElementById("s"); 